# Change these first
owner: ricenoodler # Your GitHub organization or username, where this repository lives
repo: delmundo.info-Uptime-Checker # The name of this repository

sites:
#  - name: Server Host (Hardware / Network)
#    url: https://delmundo.info
#    check: icmp-ping
#    type: globalping
  - name: NextCloud
    url: https://nextcloud.delmundo.info
  - name: Immich
    url: https://immich.delmundo.info
  - name: Jellyfin
    url: https://jellyfin.delmundo.info
  - name: Palworld Server
    url: http://palworld.delmundo.info:3000/health

status-website:
  cname: uptime.delmundo.info
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime 
  introTitle: "**delmundo.info services status**"
  introMessage: All services are updated **every 5 minutes.**
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
